CREATE TABLE IF NOT EXISTS TRANSACT
(
    TRANSACT_KEY INTEGER PRIMARY KEY AUTOINCREMENT
    ,ACCOUNT TEXT NOT NULL
    ,DATE_POSTED DATETIME NOT NULL
    ,DATE_TRANSACT DATETIME NULL
    ,DESCR TEXT NOT NULL
    ,AMMOUNT FLOAT NOT NULL
    ,CHECK_NUM INTEGER NULL
);

CREATE TABLE IF NOT EXISTS TRANSACT_VIRTUAL
(
    TRANSACT_VIRTUAL_KEY INTEGER PRIMARY KEY
    ,TRANSACT_KEY INT NOT NULL
    ,AMMOUNT FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS TAGS
(
    TAG_KEY INTEGER PRIMARY KEY
    ,TAG_NAME TEXT
    ,DESCR TEXT
    ,UNIQUE(TAG_NAME)
);

CREATE TABLE IF NOT EXISTS TRANSACT_M2M_TAG
(
    M2M_KEY INTEGER PRIMARY KEY
    ,TRANSACT_KEY INT
    ,TAG_KEY INT
    ,FOREIGN KEY(TRANSACT_KEY) REFERENCES TRANSACT(TRANSACT_KEY)
    ,FOREIGN KEY(TAG_KEY) REFERENCES TAG(TAG_KEY)
);



