INSERT INTO TRANSACT_M2M_TAG (TRANSACT_KEY, TAG_KEY)
SELECT      TRANSACT.TRANSACT_KEY, TAGS.TAG_KEY
FROM        TRANSACT
            JOIN TAGS
WHERE       instr(TRANSACT.DESCR, 'WEGMANS') > 0
            AND TAGS.TAG_NAME = 'WEGMANS'