INSERT INTO TAG_MATCH (MATCH_EXPR, MATCH_AMMOUNT_LOW, MATCH_AMMOUNT_HIGH, TAG_KEY)
SELECT  :expr MATCH_EXPR
        ,:low MATCH_AMMOUNT_LOW
        ,:high MATCH_AMMOUNT_HIGH
        ,MAX(TAG_KEY) TAG_KEY

FROM TAGS
WHERE TAG_NAME = :tag_name


-- INSERT INTO TAG_MATCH (MATCH_EXPR, MATCH_AMMOUNT_LOW, MATCH_AMMOUNT_HIGH, TAG_KEY)
-- SELECT  ':expr' MATCH_EXPR
--         ,0 MATCH_AMMOUNT_LOW
--         ,100 MATCH_AMMOUNT_HIGH
--         ,35 TAG_KEY

-- FROM TAGS
-- WHERE TAG_NAME = :tag_name

