INSERT INTO TRANSACT_M2M_TAG (TRANSACT_KEY, TAG_KEY)

SELECT      TRANSACT.TRANSACT_KEY, t.TAG_KEY
FROM        TRANSACT

            JOIN             TAGS t
            LEFT OUTER JOIN  TRANSACT_M2M_TAG tn ON  tn.TAG_KEY = t.TAG_KEY AND tn.TRANSACT_KEY = TRANSACT.TRANSACT_KEY

WHERE       (TRANSACT.AMMOUNT > 0) AND (tn.TAG_KEY IS NULL) AND (t.TAG_NAME="MISC_CREDIT")